%This function prepares the params structure depending on the specific
%experiment condition
%Project: ECoG_WM
%Author: D.T.
%Date: 25 September 2020

function params = ECoG_getParams(condition)

    if strcmp(condition, 'task_match')
        params.cue = 'match';
        params.load = 'all';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'all';
    elseif strcmp(condition, 'task_match_correct')
        params.cue = 'match';
        params.load = 'all';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'correct';
    elseif strcmp(condition, 'task_mismatch')
        params.cue = 'mismatch';
        params.load = 'all';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'all';
    elseif strcmp(condition, 'task_mismatch_correct')
        params.cue = 'mismatch';
        params.load = 'all';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'correct';
    elseif strcmp(condition, 'load_1')
        params.cue = 'all';
        params.load = 'load1';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'all';
    elseif strcmp(condition, 'load_2')
        params.cue = 'all';
        params.load = 'load2';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'all';
        params.resp = 'all';
    elseif strcmp(condition, 'load_4')
        params.cue = 'all';
        params.load = 'load4';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'all';
    elseif strcmp(condition, 'load_1_correct')
        params.cue = 'all';
        params.load = 'load1';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'correct';
    elseif strcmp(condition, 'load_2_correct')
        params.cue = 'all';
        params.load = 'load2';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'all';
        params.resp = 'correct';
    elseif strcmp(condition, 'load_4_correct')
        params.cue = 'all';
        params.load = 'load4';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'correct';
    elseif strcmp(condition, 'probe_match')
        params.cue = 'all';
        params.load = 'all';
        params.probe = 'match';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'all';
    elseif strcmp(condition, 'probe_match_correct')
        params.cue = 'all';
        params.load = 'all';
        params.probe = 'match';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'correct';
    elseif strcmp(condition, 'probe_mismatch')
        params.cue = 'all';
        params.load = 'all';
        params.probe = 'mismatch';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'all';
    elseif strcmp(condition, 'probe_mismatch_correct')
        params.cue = 'all';
        params.load = 'all';
        params.probe = 'mismatch';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'correct';
    elseif strcmp(condition, 'task_match_probe_match_correct')
        params.cue = 'match';
        params.load = 'all';
        params.probe = 'match';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'correct';
    elseif strcmp(condition, 'task_match_probe_mismatch_correct')
        params.cue = 'match';
        params.load = 'all';
        params.probe = 'mismatch';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'correct';
    elseif strcmp(condition, 'task_mismatch_probe_match_correct')
        params.cue = 'mismatch';
        params.load = 'all';
        params.probe = 'match';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'correct';
    elseif strcmp(condition, 'task_mismatch_probe_mismatch_correct')
        params.cue = 'mismatch';
        params.load = 'all';
        params.probe = 'mismatch';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'correct';
    elseif strcmp(condition, 'button_press')
        params.cue = 'all';
        params.load = 'all';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'button_press';
    elseif strcmp(condition, 'no_button_press')
        params.cue = 'all';
        params.load = 'all';
        params.probe = 'all';
        params.id = 'all';
        params.probe_id = 'all';
        params.resp = 'no_button_press';
    end
end